services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: dbuser
      POSTGRES_DB: conversations_db
    volumes:
      - ./datadir:/var/lib/postgresql/data
    command: ["postgres"]